### PR TITLE
folder2ram with mount option feature

### PR DESCRIPTION
**Pull request by gpacgpac**
Hello,

I've tweaked your script a little bit to be able to use the option field of the config file to pass options to mount binary (and if no option received, it will pass the "defaults" option to mount).

(I had an issue with executables in some of my folders => 0.3.1 script was mounting them with noexec option !).

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
Thanks for the contribution!

I would like to keep the default mount settings as "nosuid,noexec,nodev" instead of "default" so I would like to replace 
`echo "defaults";`
with
`echo "nosuid,noexec,nodev";`

and adjust the descriptions and readme accordingly.

Is that OK with you?

**Comment by gpacgpac** [comment]
That might be a possibility. But then I would recommend to add a comment 
in the config file, mentionning that if no value is written, the program 
will use nosuid,noexec,nodev (I took me some time to understand why I 
couldn't execute my files !).

I've had not enough time (nor VM / chroot jail), to test all mount 
options (impact of special chars or white spaces) => this might be 
something to do if you can.

Best regards.

Le 2019-12-02 12:37, Alberto Bursi a écrit :

**Comment by bobafetthotmail** [comment]
OK, merged. I checked and those options were chosen before the script was able to clone the permissions of the on-disk folder, so now I can do without them.
The script still acts like in your PR, I just adjusted some descriptions and added an entry in the debian changelog file so the package will be built for OpenMediaVault.

**Comment by gpacgpac** [comment]
OK great.

Have you ever proposed your program as standalone deb package (out of 
openmediavault). I discovered it via OMV, but finally ended up using it 
on standard debian install without OMV... ...but it is not that easy to 
find a deb package) ?

Le 2019-12-04 11:14, Alberto Bursi a écrit :

**Comment by bobafetthotmail** [comment]
You mean merging it in Debian? No I didn't.

I personally prefer keeping it standalone as the script itself is self-sufficient anyway, I only made the Debian package source so that OMV could build a package out of it.

If you want a deb package in Github I can make it, but it's not more useful than manually downloading the script.

**Comment by gpacgpac** [comment]
The point is that I have several computer using the tool => having a deb 
package kept updated on a repo would allow automatic update when a new 
version / a fix is available.

Le 2019-12-05 13:01, Alberto Bursi a écrit :

**Comment by bobafetthotmail** [comment]
Hm so you say making my own little Debian repo on a github folder here. 
I see what I can do.
If you want to contribute it (and test it) I will merge it.

**Comment by gpacgpac** [comment]
For sure, if it's available I'll test it !

Thanks a lot

Le 2019-12-05 15:33, Alberto Bursi a écrit :

**Pull request merged**
