### PR TITLE
ADD single folder mount/umount + ADD timestamps to sync command for logging/debugging

### PR DESCRIPTION
**Pull request by allanlaal**
also bumped version

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
thanks for the contributions, when I have time I'll test that everything still works and merge

**Comment by bobafetthotmail** [comment]
it seems that in the  "ADD single folder mount/umount " commit something (probably the IDE) added two spaces at the beginning of every line and this is breaking EOF statements (and other things).

After I cleaned the leading spaces from the file with 
`sed -i.bak 's/^[[:space:]]*//' folder2ram`

I ran some tests and everything seems fine.

can you do another commit to clean up the spaces?

**Comment by allanlaal** [comment]
didn't work. fixed and tested now
been using it :)

also Added single folder mount/umount

**Comment by bobafetthotmail** [comment]
thanks, merged

**Pull request merged**
